# Generated by Django 3.1.7 on 2021-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherReport', '0002_auto_20210321_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
